=== Makar-Ts/HayatBattleshipCalculator/schemas/modules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Module",
  "type": "object",
  "required": ["main", "activation", "modificators"],
  "properties": {
    "main": {
      "type": "object",
      "required": ["name", "type", "category", "size", "position"],
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "category": { "type": "string" },

        "class": { "type": "string" },

        "size": { "type": "number" },
        "position": {
          "type": "string",
          "enum": ["internal", "external"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      }
    },

    "activation": {
      "type": "string",
      "enum": ["passive", "active", "overload"]
    },

    "initFunctions": { "type": "string" },

    "interference": { "type": "number" },

    "cycle": { "type": "number" },
    "reload": { "type": "number" },

    "launcher": { 
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "heading": { "type": "number" },
            "vector": {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "maxItems": 2
            },
            "subgridRotation": { "type": "number" },
            "distanceOffset": { "type": "number" },
            "backupDistance": { "type": "number" },
            "recovery": {
              "type": "object",
              "properties": {
                "fuel": { "type": "number" },
                "temperature": { "type": "number" },
                "hp": {
                  "type": "object",
                  "properties": {
                    "hull": { "type": "number" },
                    "armor": { "type": "number" },
                    "barrier": { "type": "number" }
                  }
                }
              }
            }
          }
        },
        {
          "type": "object",
          "required": ["instances"],
          "properties": {
            "heading": { "type": "number" },
            "instances": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["vector", "headingOffset", "distanceOffset", "subgrid"],
                "properties": {
                  "vector": {
                    "type": "array",
                    "items": { "type": "number" },
                    "minItems": 2,
                    "maxItems": 2
                  },
                  "headingOffset": { "type": "number" },
                  "distanceOffset": { "type": "number" },
                  "subgridRotation": { "type": "number" },

                  "fire": {
                    "type": "object",
                    "required": ["type", "delay"],
                    "properties": {
                      "type": { "type": "string" },
                      "delay": {
                        "oneOf": [
                          { "type": "number" },
                          {
                            "type": "array",
                            "items": { "type": "number" }
                          }
                        ]
                      }
                    }
                  },

                  "subgrid": {
                    "type": "object",
                    "required": ["class", "dataRef"],
                    "properties": {
                      "class": { "type": "string" },
                      "dataRef": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },

    "additionalInfo": {
      "type": "object"
    },

    "effects": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["class", "isWeapon", "activateOn"],
        "properties": {
          "class": { "type": "string", "minLength": 1 },
          "activateOn": { 
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["passive", "active", "overload"]
            }
          },
          "settings": {
            "type": "object"
          }
        }
      }
    },

    "modificators": {
      "type": "object",
      "required": ["offline", "online", "active", "overload"],
      "properties": {
        "offline": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "online": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "active": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "overload": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        }
      }
    },

    "external": {
      "type": "object",
      "patternProperties": {
        "^.*$": { 
          "type": "string",
          "pattern": "^([\\w-_]+(\\/|.json))+$"
        }
      }
    }
  },

  "definitions": {
    "modRecord": {
      "type": "object",
      "required": ["target", "characteristic", "modificationType", "modificator"],
      "properties": {
        "target": {
          "type": "string",
          "enum": ["this", "target", "area", "subgrid"]
        },
        "affectedLayers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["battleship", "missile", "drone", "shell", "mine"]
          }
        },
        "characteristic": { "type": "string" },

        "modificationType": {
          "type": "string",
          "enum": ["number", "percent"]
        },

        "modificator": {
          "oneOf": [
            { "type": "number" },
            { "type": "string" }
          ]
        },

        "isAffectedByInterference": { "type": "boolean" }
      }
    }
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/microdistortiondrive-s.json
{
  "main": {
    "name": "Микродисторционный привод S",
    "type": "Мобильность",
    "category": "Микродисторционный привод",

    "size": 1,
    "position": "internal",
    "tags": ["microdistortiondrive", "signaturepenalty"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 0,
  
  "interference": -1,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -10,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.acceleration",
        "modificationType": "percent",
        "modificator": 1.5,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.03,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.body.signature",
        "modificationType": "percent",
        "modificator": 2.5,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/resistance/universal-armor-plating.json
{
  "main": {
    "name": "Активная универсальная обшивка",
    "type": "Сопротивляемость",
    "category": "Реактивная мембрана брони",

    "size": 2,
    "position": "internal",
    "tags": ["armorresistanceextender", "omniresistextender"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 0,
  
  "interference": -0.0625,

  "additionalInfo": {
    "effectiveness": 0.25,
    "baseHeating": 0.04,
    "baseConsumption": -3
  },

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseConsumption * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.capacitor_consumption_modifier",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseHeating * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.heating_modifier",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.resistance.kinetic.armor",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.effectiveness * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.effectiveness_modifier",
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.resistance.high_explosive.armor",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.effectiveness * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.effectiveness_modifier",
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.resistance.electro_magnetic.armor",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.effectiveness * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.effectiveness_modifier",
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.resistance.thermal.armor",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.effectiveness * parent.currentCharacteristics.constant.modulemodifier.engineering.hardener.active.armor.effectiveness_modifier",
        "isAffectedByInterference": true
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/shiptype-profile/kr-pioner-stp.json
{
  "main": {
    "name": "Проф. Особенность типа «Пионер»",
    "type": "Проф. Особенность типа",
    "category": "Проф. Особенность Фрегата",

    "size": 0,
    "position": "internal",
    "tags": ["stp"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
        {
        "target": "this",
        "characteristic": "constant.modulemodifier.offence.ballistic.damage_modifier",
        "modificationType": "number",
        "modificator": 0.2,
        "isAffectedByInterference": false
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/afterburner-s.json
{
  "main": {
    "name": "Форсажная камера S",
    "type": "Мобильность",
    "category": "Форсажная камера",

    "size": 1,
    "position": "internal",
    "tags": ["afterburner", "maneuverbuff"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 1,
  
  "interference": -1,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.acceleration",
        "modificationType": "percent",
        "modificator": 0.4,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.03,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/test.json
{
  "main": {
    "name": "Дополнительные РСУ / test",
    "type": "Мобильность",
    "category": "Маневровые ускорители",

    "size": 1,
    "position": "internal",
    "tags": []
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -8,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.body.signature",
        "modificationType": "percent",
        "modificator": 0.8,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.01,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.maneuverability",
        "modificationType": "number",
        "modificator": 2,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/regeneration/neosteel-coating.json
{
  "main": {
    "name": "Неостальная броня",
    "type": "Восстановление",
    "category": "Система активного ремонта",

    "size": 2,
    "position": "internal",
    "tags": ["armorrepairer"]
  },
  "activation": "active",
  "interference": -0.09,

  "reload": 3,
  "cycle": 1,

  "additionalInfo": {
    "baseRepair": 250,
    "baseHeating": 0.20,
    "baseConsumption": -30
  },

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseConsumption * parent.currentCharacteristics.constant.modulemodifier.engineering.armor.active_repair_consumption",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseHeating * parent.currentCharacteristics.constant.modulemodifier.engineering.armor.active_repair_heating",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "dynamic.hp.armor",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseRepair * parent.currentCharacteristics.constant.modulemodifier.engineering.armor.active_repair_modifier",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/EW/res-vampire.json
{
  "main": {
    "name": "RES Vampire",
    "type": "РЭБ",
    "category": "Система нейтрализации накопителя",

    "size": 2,
    "position": "internal",
    "tags": ["capacitorew", "ew"]
  },
  "activation": "active",
  "interference": 0,

  "additionalInfo": {
    "recharge": 1
  },

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": 5,
        "isAffectedByInterference": false
      },
      {
        "target": "target",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -5,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/pilot-skills-perks/intellectualflexibility-skill.json
{
  "main": {
    "name": "Интеллектуальная гибкость",
    "type": "Навык",
    "category": "Интеллектуальная гибкость",

    "size": 0,
    "position": "internal",
    "tags": ["skill"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.resistance.EW",
        "modificationType": "percent",
        "modificator": 1.1,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}
