=== Makar-Ts/HayatBattleshipCalculator/schemas/modules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Module",
  "type": "object",
  "required": ["main", "activation", "modificators"],
  "properties": {
    "main": {
      "type": "object",
      "required": ["name", "type", "category", "size", "position"],
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "category": { "type": "string" },

        "class": { "type": "string" },

        "size": { "type": "number" },
        "position": {
          "type": "string",
          "enum": ["internal", "external"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      }
    },

    "activation": {
      "type": "string",
      "enum": ["passive", "active", "overload"]
    },

    "initFunctions": { "type": "string" },

    "interference": { "type": "number" },

    "cycle": { "type": "number" },
    "reload": { "type": "number" },

    "launcher": { 
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "heading": { "type": "number" },
            "vector": {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "maxItems": 2
            },
            "subgridRotation": { "type": "number" },
            "distanceOffset": { "type": "number" },
            "backupDistance": { "type": "number" },
            "recovery": {
              "type": "object",
              "properties": {
                "fuel": { "type": "number" },
                "temperature": { "type": "number" },
                "hp": {
                  "type": "object",
                  "properties": {
                    "hull": { "type": "number" },
                    "armor": { "type": "number" },
                    "barrier": { "type": "number" }
                  }
                }
              }
            }
          }
        },
        {
          "type": "object",
          "required": ["instances"],
          "properties": {
            "heading": { "type": "number" },
            "instances": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["vector", "headingOffset", "distanceOffset", "subgrid"],
                "properties": {
                  "vector": {
                    "type": "array",
                    "items": { "type": "number" },
                    "minItems": 2,
                    "maxItems": 2
                  },
                  "headingOffset": { "type": "number" },
                  "distanceOffset": { "type": "number" },
                  "subgridRotation": { "type": "number" },

                  "fire": {
                    "type": "object",
                    "required": ["type", "delay"],
                    "properties": {
                      "type": { "type": "string" },
                      "delay": {
                        "oneOf": [
                          { "type": "number" },
                          {
                            "type": "array",
                            "items": { "type": "number" }
                          }
                        ]
                      }
                    }
                  },

                  "subgrid": {
                    "type": "object",
                    "required": ["class", "dataRef"],
                    "properties": {
                      "class": { "type": "string" },
                      "dataRef": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },

    "additionalInfo": {
      "type": "object"
    },

    "effects": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["class", "isWeapon", "activateOn"],
        "properties": {
          "class": { "type": "string", "minLength": 1 },
          "activateOn": { 
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["passive", "active", "overload"]
            }
          },
          "settings": {
            "type": "object"
          }
        }
      }
    },

    "modificators": {
      "type": "object",
      "required": ["offline", "online", "active", "overload"],
      "properties": {
        "offline": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "online": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "active": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "overload": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        }
      }
    },

    "external": {
      "type": "object",
      "patternProperties": {
        "^.*$": { 
          "type": "string",
          "pattern": "^([\\w-_]+(\\/|.json))+$"
        }
      }
    }
  },

  "definitions": {
    "modRecord": {
      "type": "object",
      "required": ["target", "characteristic", "modificationType", "modificator"],
      "properties": {
        "target": {
          "type": "string",
          "enum": ["this", "target", "area", "subgrid"]
        },
        "affectedLayers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["battleship", "missile", "drone", "shell", "mine"]
          }
        },
        "characteristic": { "type": "string" },

        "modificationType": {
          "type": "string",
          "enum": ["number", "percent"]
        },

        "modificator": {
          "oneOf": [
            { "type": "number" },
            { "type": "string" }
          ]
        },

        "isAffectedByInterference": { "type": "boolean" }
      }
    }
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/shiptype-profile/gc-mantis-stp.json
{
  "main": {
    "name": "Проф. Особенность типа «Богомол»",
    "type": "Проф. Особенность типа",
    "category": "Проф. Особенность Фрегата",

    "size": 0,
    "position": "internal",
    "tags": ["stp"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
        {
        "target": "this",
        "characteristic": "constant.modulemodifier.engineering.armor.active_repair_consumption",
        "modificationType": "percent",
        "modificator": 0.5,
        "isAffectedByInterference": false
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/thermodynamics/internalradiator.json
{
  "main": {
    "name": "Внутренний радиатор M",
    "type": "Термодинамика",
    "category": "Система изоляции",

    "size": 2,
    "position": "internal",
    "tags": ["internalradiator","temperatureextender","extender"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.temperature",
        "modificationType": "percent",
        "modificator": 1.5,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/pilot-drug-effects/drivedose.json
{
  "main": {
    "name": "«Drivedose»",
    "type": "Наркотик",
    "category": "Доза-2",

    "size": 0,
    "position": "internal",
    "tags": ["psychoserocin"]
  },
  "activation": "passive",
  "interference": -1,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.maneuverability",
        "modificationType": "number",
        "modificator": 1,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/rss.json
{
  "main": {
    "name": "Дополнительные РСУ M",
    "type": "Мобильность",
    "category": "Маневровые ускорители",

    "size": 2,
    "position": "internal",
    "tags": ["rss", "maneuverbuff", "signaturesupressor"]
  },
  "activation": "active",
  "interference": 0,

  "additionalInfo": {
    "recharge": 1
  },

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -8,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.body.signature",
        "modificationType": "percent",
        "modificator": 0.8,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.01,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.maneuverability",
        "modificationType": "number",
        "modificator": 2,
        "isAffectedByInterference": true
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/thermodynamics/external-radiator-s.json
{
  "main": {
    "name": "Внешний радиатор S",
    "type": "Термодинамика",
    "category": "Радиатор",

    "size": 1,
    "position": "internal",
    "tags": ["externalradiator","cooler"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 1,
  
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -2,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.body.signature",
        "modificationType": "percent",
        "modificator": 0.08,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": -0.04,
        "isAffectedByInterference": true
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/microdistortiondrive.json
{
  "main": {
    "name": "Микродисторционный привод M",
    "type": "Мобильность",
    "category": "Микродисторционный привод",

    "size": 2,
    "position": "internal",
    "tags": ["microdistortiondrive", "signaturepenalty"]
  },
  "activation": "active",
  "interference": -100,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -20,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.acceleration",
        "modificationType": "percent",
        "modificator": 3.5,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.05,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.signature",
        "modificationType": "percent",
        "modificator": 4,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/resistance/shieldextender.json
{
  "main": {
    "name": "Интерферентная ячейка щита",
    "type": "Сопротивляемость",
    "category": "Расширитель Щита",

    "size": 2,
    "position": "internal",
    "tags": ["shieldextender", "signaturepenalty"]
  },
  "activation": "passive",
  "interference": -0.09,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.body.signature",
        "modificationType": "percent",
        "modificator": 1.1,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.hp.barrier",
        "modificationType": "percent",
        "modificator": 1.3,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/EW/lyer.json
{
  "main": {
    "name": "Система радиоподавления «Лжец»",
    "type": "РЭБ",
    "category": "Система радиоподавления",

    "size": 2,
    "position": "internal",
    "tags": ["jammer", "contactjammer", "ew"]
  },
  "activation": "active",
  "cycle": 1,
  "reload": 0,
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": "0.01 * parent.currentCharacteristics.constant.module_modifiers['offence>EW>heating_modifier']",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": "-6 * parent.currentCharacteristics.constant.module_modifiers['offence>EW>capacitor_consumption_modifier']",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}
