=== Makar-Ts/HayatBattleshipCalculator/schemas/modules.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Module",
  "type": "object",
  "required": ["main", "activation", "modificators"],
  "properties": {
    "main": {
      "type": "object",
      "required": ["name", "type", "category", "size", "position"],
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "category": { "type": "string" },

        "class": { "type": "string" },

        "size": { "type": "number" },
        "position": {
          "type": "string",
          "enum": ["internal", "external"]
        },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      }
    },

    "activation": {
      "type": "string",
      "enum": ["passive", "active", "overload"]
    },

    "initFunctions": { "type": "string" },

    "interference": { "type": "number" },

    "cycle": { "type": "number" },
    "reload": { "type": "number" },

    "launcher": { 
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "heading": { "type": "number" },
            "vector": {
              "type": "array",
              "items": { "type": "number" },
              "minItems": 2,
              "maxItems": 2
            },
            "subgridRotation": { "type": "number" },
            "distanceOffset": { "type": "number" },
            "backupDistance": { "type": "number" },
            "recovery": {
              "type": "object",
              "properties": {
                "fuel": { "type": "number" },
                "temperature": { "type": "number" },
                "hp": {
                  "type": "object",
                  "properties": {
                    "hull": { "type": "number" },
                    "armor": { "type": "number" },
                    "barrier": { "type": "number" }
                  }
                }
              }
            }
          }
        },
        {
          "type": "object",
          "required": ["instances"],
          "properties": {
            "heading": { "type": "number" },
            "instances": {
              "type": "array",
              "items": {
                "type": "object",
                "required": ["vector", "headingOffset", "distanceOffset", "subgrid"],
                "properties": {
                  "vector": {
                    "type": "array",
                    "items": { "type": "number" },
                    "minItems": 2,
                    "maxItems": 2
                  },
                  "headingOffset": { "type": "number" },
                  "distanceOffset": { "type": "number" },
                  "subgridRotation": { "type": "number" },

                  "fire": {
                    "type": "object",
                    "required": ["type", "delay"],
                    "properties": {
                      "type": { "type": "string" },
                      "delay": {
                        "oneOf": [
                          { "type": "number" },
                          {
                            "type": "array",
                            "items": { "type": "number" }
                          }
                        ]
                      }
                    }
                  },

                  "subgrid": {
                    "type": "object",
                    "required": ["class", "dataRef"],
                    "properties": {
                      "class": { "type": "string" },
                      "dataRef": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },

    "additionalInfo": {
      "type": "object"
    },

    "effects": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["class", "isWeapon", "activateOn"],
        "properties": {
          "class": { "type": "string", "minLength": 1 },
          "activateOn": { 
            "type": "array",
            "items": {
              "type": "string",
              "enum": ["passive", "active", "overload"]
            }
          },
          "settings": {
            "type": "object"
          }
        }
      }
    },

    "modificators": {
      "type": "object",
      "required": ["offline", "online", "active", "overload"],
      "properties": {
        "offline": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "online": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "active": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        },
        "overload": {
          "type": "array",
          "items": { "$ref": "#/definitions/modRecord" }
        }
      }
    },

    "external": {
      "type": "object",
      "patternProperties": {
        "^.*$": { 
          "type": "string",
          "pattern": "^([\\w-_]+(\\/|.json))+$"
        }
      }
    }
  },

  "definitions": {
    "modRecord": {
      "type": "object",
      "required": ["target", "characteristic", "modificationType", "modificator"],
      "properties": {
        "target": {
          "type": "string",
          "enum": ["this", "target", "area", "subgrid"]
        },
        "affectedLayers": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["battleship", "missile", "drone", "shell", "mine"]
          }
        },
        "characteristic": { "type": "string" },

        "modificationType": {
          "type": "string",
          "enum": ["number", "percent"]
        },

        "modificator": {
          "oneOf": [
            { "type": "number" },
            { "type": "string" }
          ]
        },

        "isAffectedByInterference": { "type": "boolean" }
      }
    }
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/subgrid-support/test/better-explosives.json
{
  "main": {
    "name": "Улучшенная взрывчатка",
    "type": "Модификатор субгридов",
    "category": "Мод. взрывчатки",

    "size": 1,
    "position": "internal",
    "tags": []
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "subgrid",
        "affectedLayers": ["missile"],
        "characteristic": "constant.body.subgrid.explosion.radius",
        "modificationType": "percent",
        "modificator": 1.2,
        "isAffectedByInterference": false
      },
      {
        "target": "subgrid",
        "affectedLayers": ["missile"],
        "characteristic": "constant.body.subgrid.explosion.effect.damage.high_explosive",
        "modificationType": "percent",
        "modificator": 1.4,
        "isAffectedByInterference": false
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/shiptype-profile/zd-moth-stp.json
{
  "main": {
    "name": "Проф. Особенность типа «Мотылёк»",
    "type": "Проф. Особенность типа",
    "category": "Проф. Особенность Эсминца",

    "size": 0,
    "position": "internal",
    "tags": ["stp"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.body.subgrid.fuel",
        "modificationType": "percent",
        "modificator": 0.75,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.body.subgrid.acceleration",
        "modificationType": "percent",
        "modificator": 1.5,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.body.subgrid.explosion.effect.damage.high_explosive",
        "modificationType": "percent",
        "modificator": 1.15,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.modulemodifier.engineering.barrier.resonance.tendency",
        "modificationType": "number",
        "modificator": 0.15,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/regeneration/active-barrier-recharger-m.json
{
  "main": {
    "name": "Модуль откачки барьера M",
    "type": "Восстановление",
    "category": "Система откачки барьера",

    "size": 2,
    "position": "internal",
    "tags": ["shieldrecharger"]
  },
  "activation": "active",
  "interference": 0,

  "reload": 0,
  "cycle": 1,

  "additionalInfo": {
    "baseRecharge": 80,
    "baseHeating": 0.07,
    "baseConsumption": -15
  },

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
      {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseConsumption * parent.currentCharacteristics.constant.modulemodifier.engineering.barrier.active_recharge_consumption",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseHeating * parent.currentCharacteristics.constant.modulemodifier.engineering.barrier.active_recharge_heating",
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "dynamic.hp.barrier",
        "modificationType": "number",
        "modificator": "module.characteristics.additionalInfo.baseRecharge * parent.currentCharacteristics.constant.modulemodifier.engineering.barrier.active_recharge_modifier",
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/jumpdrive.json
{
  "main": {
    "name": "Прыжковый двигатель L",
    "type": "Мобильность",
    "category": "Прыжковый портал",

    "size": 3,
    "position": "internal",
    "tags": ["jumpdrive"]
  },
  "activation": "active",
  "interference": -100,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -50,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.jumpdistance",
        "modificationType": "number",
        "modificator": 100000,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.1,
        "isAffectedByInterference": false
      }
    ],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/subgrid-support/test/mod-drone-nav-system.json
{
  "main": {
    "name": "Мод. нав. системы дронов",
    "type": "Модификатор субгридов",
    "category": "Мод. навигации",

    "size": 1,
    "position": "internal",
    "tags": []
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "subgrid",
        "affectedLayers": ["drone"],
        "characteristic": "constant.body.subgrid.drone.safe_distance",
        "modificationType": "number",
        "modificator": 2500,
        "isAffectedByInterference": false
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/construction/hangar.json
{
  "main": {
    "name": "Малый ангар M",
    "type": "Конструкция",
    "category": "Ангар",

    "size": 2,
    "position": "internal",
    "tags": ["hangar"]
  },
  "activation": "passive",
  "interference": 0,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.body.containers.hangar",
        "modificationType": "number",
        "modificator": 25,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/resistance/tunsgencoating.json
{
  "main": {
    "name": "Дополнительный слой вольфрама",
    "type": "Сопротивляемость",
    "category": "Доп. Бронирование",

    "size": 2,
    "position": "internal",
    "tags": ["armorextender", "maneuverpenalty"]
  },
  "activation": "passive",
  "interference": -0.09,

  "modificators": {
    "offline": [],
    "online": [
      {
        "target": "this",
        "characteristic": "constant.acceleration",
        "modificationType": "percent",
        "modificator": 0.9,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.hp.armor",
        "modificationType": "percent",
        "modificator": 1.3,
        "isAffectedByInterference": true
      }
    ],
    "active": [],
    "overload": []
  }
}

=== Makar-Ts/HayatBattleshipCalculator/modules/mobility/afterburner.json
{
  "main": {
    "name": "Форсажная камера M",
    "type": "Мобильность",
    "category": "Форсажная камера",

    "size": 2,
    "position": "internal",
    "tags": ["afterburner", "maneuverbuff"]
  },
  "activation": "active",
  "interference": -1,

  "modificators": {
    "offline": [],
    "online": [],
    "active": [
        {
        "target": "this",
        "characteristic": "constant.capacitor.generation",
        "modificationType": "number",
        "modificator": -15,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.acceleration",
        "modificationType": "percent",
        "modificator": 1.8,
        "isAffectedByInterference": true
      },
      {
        "target": "this",
        "characteristic": "constant.heating",
        "modificationType": "number",
        "modificator": 0.06,
        "isAffectedByInterference": false
      },
      {
        "target": "this",
        "characteristic": "constant.maneuverability",
        "modificationType": "number",
        "modificator": 1,
        "isAffectedByInterference": true
      }
    ],
    "overload": []
  }
}
